---
apiVersion: v1
kind: Service
metadata:
  namespace: capstone
  labels:
    name: appointmentservice
  name: appointmentservicesvc
spec:
  ports:
  - port: 8090
    targetport: 8090
  selector:
    name: appointmentservice
...

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: capstone
  labels:
    name: appointmentservice
  name: appointmentservice
spec:
  replicas: 1
  selector:
    matchLabels:
      name: appointmentservice
  template:
    metadata:
      labels:
        name: appointmentservice
    spec:
      containers:
      - image: shubh1254/appointmentservice:latest
        name: appointment-service-container
        env:
        - name: eureka.client.serviceUrl.defaultZone
          value: http://eurekaserversvc:8761/eureka
        - name: spring.data.mongodb.uri
          value: mongodb://mongodbservicesvc:27017/fitpro
        ports:
        - containerPort: 8090
...
