---
apiVersion: v1
kind: Service
metadata:
  
  namespace: capstone
  labels:
    name: mongodbservice
  name: mongodbservicesvc
spec:
  ports:
  - port: 27017
  clusterIP: None
  selector:
    name: mongodbservice
...

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: capstone
  labels:
    name: mongodbservice
  name: mongodbservice
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongodbservice
  template:
    metadata:
      labels:
        name: mongodbservice
    spec:
      containers:
      - image: shubh1254/mongo:latest
        name: mongo-container
        ports:
        - containerPort: 27017
      restartPolicy: Always
...