---
apiVersion: v1
kind: Service
metadata:
  
  namespace: capstone
  labels:
    name: product-webapp
  name: productwebappsvc
spec:
  ports:
  - port: 8087
    targetPort: 8087
  selector:
    name: product-webapp
...

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: capstone
  labels:
    name: product-webapp
  name: product-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      name: product-webapp
  template:
    metadata:
      labels:
        name: product-webapp
    spec:
      containers:
      - image: shubh1254/product-webapp:latest
        name: product-webapp
        env:
        - name: eureka.client.serviceUrl.defaultZone
          value: http://eurekaserversvc:8761/eureka
        ports:
        - containerPort: 8087
...
