---
apiVersion: v1
kind: Service
metadata:
  
  namespace: capstone
  labels:
    name: rabbitmq
  name: rabbitmqsvc
spec:
  type: NodePort
  ports:
  - port: 5672
    targetport: 5672
    nodePort: 30046
  - port: 15672
    targetport: 15672
    nodePort: 30047
  selector:
    name: rabbitmq
...

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: capstone
  labels:
    name: rabbitmq
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      name: rabbitmq
  template:
    metadata:
      labels:
        name: rabbitmq
    spec:
      containers:
      - image: shubh1254/rabbitmq:latest
        name: rabbitmq
        ports:
        - containerPort: 5672
        - containerPort: 15672
      restartPolicy: Always
...