---
apiVersion: v1
kind: Service
metadata:
  namespace: capstone
  labels:
    name: userservice
  name: userservicesvc
spec:
  type: ClusterIP
  ports:
  - port: 8083
    targetport: 8083
  selector:
    name: userservice
...

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: capstone
  labels:
    name: userservice
  name: userservice
spec:
  replicas: 1
  selector:
    matchLabels:
      name: userservice
  template:
    metadata:
      labels:
        name: userservice
    spec:
      containers:
      - image: shubh1254/userservice:latest
        name: user-service-container
        env:
        - name: enthusiast_home_page_url
          value: http://productwebappsvc:8087/#/innovators
        - name: expert_home_page_url
          value: http://productwebappsvc:8087/#/experts
        - name: enthusiast_redirect_url
          value: http://userservicesvc:8083/api/v1/authorize/enthusiast/complete
        - name: expert_redirect_url
          value: http://userservicesvc:8083/api/v1/authorize/expert/complete
        - name: eureka.client.serviceUrl.defaultZone
          value: http://eurekaserversvc:8761/eureka
        - name: spring.data.mongodb.host
          value: mongodbservicesvc
        - name: Domain
          value: localhosteureka.client.serviceUrl.defaultZone=http://eurekaserversvc:8761/eureka
        - name: logout_redirect_url
          value: http://productwebappsvc:8087/#/
        ports:
        - containerPort: 8083
...